### ISSUE TITLE
Instalar sonarlint en eclipse

### ISSUE THREAD

**Issue by jschenfeld** [Arielcm/Automation-Test#3]
Ir a Help -> Eclipse Marketplace. Buscar SonarLint y seguir los pasos de instalación.

Este plugin te mostrará los errores más comunes, por ejemplo, el nombre de los métodos siempre empiezan con minúsculas, cuando se usan más de una palabra en el nombre de un método o variable se usa mayúscula y no guiones.

**Comment by Arielcm** [comment]
Instalado SonarLint  en Eclipse
