### ISSUE TITLE
método create_Account

### ISSUE THREAD

**Issue by jschenfeld** [Arielcm/Automation-Test#4]
1. El nombre debería ser createAccount
2. El mismo no debería recibir más de 5 parámetros, para evitar pasar tanto parámetros se debe usar una clase Persona con todos los atributos necesarios, leer sobre el patrón de diseño DTO (Data Transfer Object).
3. Es preferible usar los Assert de TestNG en vez de los AssertJUnit, estos solo fueron creados para tener compatibilidad en un proyecto donde se está migrando de Junt a TestNG.

**Comment by Arielcm** [comment]
Solucionados todos los puntos
