### ISSUE TITLE
AddPersonas

### ISSUE THREAD

**Issue by jschenfeld** [Arielcm/Automation-Test#6]
1. Darle formato al archivo (botón derecho -> source -> Format)
2. No declarar la variable nomp si no va a ser usada, directamente devolver el valor.
3. Lo mismo que en el paso 2 para el método apellido.
4. Si los métodos de la clase AddPersonas no guardan ningún estada agregarles la modificador static y evitar instanciar la clase.

**Comment by Arielcm** [comment]
Formateado y eliminadas las variables nomp y ape....metodos estaticos creados y eliminada la instanciacion de la clase
